[package]
name = "scd30-modbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
embedded-hal = "0.2.7"
nb = "1.0.0"
smol = "1.2.5"